<?php

namespace MyAutoBundle\Repository;

/**
 * AutoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutoRepository extends \Doctrine\ORM\EntityRepository
{
}
