<?php

namespace MyAutoBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
