<?php

namespace MyAutoBundle\Repository;
use MyAutoBundle\Entity\Auto;
use MyAutoBundle\Entity\User;

/**
 * AutoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFavorites(User $user)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();

        $qb->select('a')
            ->from(Auto::class, 'a')
            ->leftJoin('a.favoritedUsers', 'j')
            ->where('j.id = :id')
            ->setParameter('id', $user->getId());

        return $qb->getQuery()->getResult();
        getRepository('MyAutoBundle:Auto')->findBy(array('favoritedUsers' => $user->getId()));

        return $qb;
    }
}
