services:
    my_auto.car:
        class: MyAutoBundle\Service\CarService
        arguments: ['@doctrine.orm.entity_manager']

    auto.entity_listener:
        arguments: ['@monolog.logger', '@es.manager']
        class: MyAutoBundle\Entity\Listener\AutoListener
        tags:
            - { name: doctrine.orm.entity_listener }
