services:
    stack_exchange.form_type.question:
        class: StackExchangeBundle\Form\QuestionType
        arguments: ["@stack_exchange.model.question.class"]

    stack_exchange.form_type.answer:
        class: StackExchangeBundle\Form\AnswerType
        arguments: ["@stack_exchange.model.question.class"]

    stack_exchange.form_type.vote:
        class: StackExchangeBundle\Form\VoteType

    stack_exchange.form_type.comment:
        class: StackExchangeBundle\Form\CommentType

    stack_exchange.form_factory.question:
        class: StackExchangeBundle\FormFactory\QuestionFormFactory
        arguments: ["@form.factory", "@stack_exchange.form_type.question", "%%stack_exchange.form.question.name%%"]

    stack_exchange.form_factory.answer:
        class: StackExchangeBundle\FormFactory\AnswerFormFactory
        arguments: ["@form.factory", "@stack_exchange.form_type.answer", "%%stack_exchange.form.answer.name%%"]

    stack_exchange.form_factory.vote:
        class: StackExchangeBundle\FormFactory\VoteFormFactory
        arguments: ["@form.factory", "@stack_exchange.form_type.vote", "%%stack_exchange.form.vote.name%%"]

    stack_exchange.form_factory.comment:
        class: StackExchangeBundle\FormFactory\CommentFormFactory
        arguments: ["@form.factory", "@stack_exchange.form_type.comment", "%%stack_exchange.form.comment.name%%"]