#
# This file is part of the FOSCommentBundle package.
#
# (c) FriendsOfSymfony <http://friendsofsymfony.github.com/>
#
# This source file is subject to the MIT license that is bundled
# with this source code in the file LICENSE.
#
stack_exchange_api:
    type: rest
    resource: StackExchangeBundle\Controller\VoteController
    name_prefix: stack_exchange_
