<?php

namespace StackExchangeBundle\Repository;

/**
 * QuestionCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuestionCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
