imports:
    - { resource: forms.yml }
    - { resource: listeners.yml }

services:
    multi_blog.manager.page:
        class: MultiBlogBundle\Entity\PageManager
        arguments: ["@event_dispatcher","@doctrine.orm.entity_manager"]

    multi_blog.manager.tag:
        class: MultiBlogBundle\Entity\TagManager
        arguments: ["@event_dispatcher","@doctrine.orm.entity_manager"]