parameters:
    car_show.form.picture_select.name: car_show_picture_select

imports:
    - { resource: forms.yml }

services:
    car_show.car:
        class: CarShowBundle\Service\CarService
        arguments: ['@doctrine.orm.entity_manager']

    car_show.car.entity_listener:
        arguments: ['@monolog.logger', '@es.manager']
        class: CarShowBundle\Entity\Listener\AutoListener
        tags:
            - { name: doctrine.orm.entity_listener }

    car_show.manager.car:
        class: CarShowBundle\Entity\CarManager
        arguments: ["@event_dispatcher","@doctrine.orm.entity_manager"]
