parameters:
    car_show.form.picture_select.name: car_show_picture_select

imports:
    - { resource: listeners.yml }
    - { resource: forms.yml }

services:
    car_show.model.car.class:
        class: CarShowBundle\Entity\Car

    car_show.car:
        class: CarShowBundle\Service\CarService
        arguments: ['@doctrine.orm.entity_manager']

    car_show.manager.car:
        class: CarShowBundle\Entity\CarManager
        arguments: ["@event_dispatcher","@doctrine.orm.entity_manager"]

    car_show.manager.post:
        class: CarShowBundle\Entity\PostManager
        arguments: ["@event_dispatcher","@doctrine.orm.entity_manager"]

    car_show.manager.service_history:
        class: CarShowBundle\Entity\ServiceHistoryManager
        arguments: ["@event_dispatcher","@doctrine.orm.entity_manager"]

